config/routes.rb
Sondeo::Application.routes.draw do
  resources :periodo_electorales do
    member do
      get :show_resultados
      get :show_proyecto
      get :nuevo_anteproyecto
      post :nuevo_proyecto
    end
    collection do
      get :eliminar_proyecto
    end
  end

  resources :periodo_propuestas do
    collection do
      get :nueva_propuesta
      get :propuestas 
    end
  end

  resources :propuestas do 
    collection do
      get :buscar
    end
  end

  resources :municipios do
    collection do
      get "busca_provincias"
    end
  end

  resources :provincias 

  resources :paises 

  get "main/index"

  resources :users do
    collection do
      post 'cambiar_pass'
    end
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'iniciar' => 'sessions#iniciar', :as => :iniciar
  
  match 'mobile' => 'mobile#index', :as => :mobile

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :barrios do
    collection do
      get "busca_municipios"
    end
  end

  resources :ciudadanos do
    member do
      get "anteproyectos"
      post "registrar_voto"
      get 'elecciones_cerradas'
    end

    collection do
      get 'busca_barrios'
      get 'periodos'
    end
  end

  root :to => "main#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/propuesta.rb
class Propuesta < ActiveRecord::Base
	belongs_to :user
	belongs_to :periodo_propuesta

	validates :descripcion, :presence => true
end

app/controllers/propuestas_controller.rb
class PropuestasController < ApplicationController
  before_filter :login_required, :except=>[:create]
  # GET /propuestas
  # GET /propuestas.json
  def index
    @propuestas = Propuesta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @propuestas }
    end
  end

  # GET /propuestas/1
  # GET /propuestas/1.json
  def show
    @propuesta = Propuesta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @propuesta }
    end
  end

  # GET /propuestas/new
  # GET /propuestas/new.json
  def new
    @propuesta = Propuesta.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @propuesta }
    end
  end

  # GET /propuestas/1/edit
  def edit
    @propuesta = Propuesta.find(params[:id])
  end

  # POST /propuestas
  # POST /propuestas.json
  def create
    # raise "error"
    @propuesta = Propuesta.new(params[:propuesta])

    respond_to do |format|
      if @propuesta.save
        format.html { redirect_to propuestas_periodo_propuestas_path(:id=>@propuesta.periodo_propuesta.id), :notice => 'Propuesta fue creado correctamente.' }
        format.json { render :json => {:status=>'OK',:message=>'Propuesta registrada'}.to_json}
      else
        format.html { render :action => "new" }
        format.json { render :json => {:status=>'ERROR'}.to_json}
      end
    end
  end

  # PUT /propuestas/1
  # PUT /propuestas/1.json
  def update
    @propuesta = Propuesta.find(params[:id])

    respond_to do |format|
      if @propuesta.update_attributes(params[:propuesta])
        format.html { redirect_to propuestas_periodo_propuestas_path(:id=>@propuesta.periodo_propuesta.id), :notice => 'Propuesta fue actualizado correctamente.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @propuesta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /propuestas/1
  # DELETE /propuestas/1.json
  def destroy
    @propuesta = Propuesta.find(params[:id])
    @propuesta.destroy

    respond_to do |format|
      format.html { redirect_to  propuestas_periodo_propuestas_path(:id=>@propuesta.periodo_propuesta.id) }
      format.json { head :ok }
    end
  end

  def buscar
    @periodo_propuestas=PeriodoPropuesta.where('barrio_id = ? and ? <= fecha_fin', params[:barrio_id],Date.today)
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/propuestas_helper.rb
module PropuestasHelper
end

app/views/propuestas/_busqueda.html.haml
.accordion
  - @periodo_propuestas.each do |pp|
    .accordionButton
      %h3
        =pp.descripcion
    .accordionContent
      - pp.propuestas.each do |p|

        .accordion-content
          #{p.descripcion}
        .clear


:javascript
  $(document).ready(function() {
     
    //ACCORDION BUTTON ACTION (ON CLICK DO THE FOLLOWING)
    $('.accordionButton').click(function() {

      //REMOVE THE ON CLASS FROM ALL BUTTONS
      $('.accordionButton').removeClass('on');
        
      //NO MATTER WHAT WE CLOSE ALL OPEN SLIDES
      $('.accordionContent').slideUp('normal');
     
      //IF THE NEXT SLIDE WASN'T OPEN THEN OPEN IT
      if($(this).next().is(':hidden') == true) {
        
        //ADD THE ON CLASS TO THE BUTTON
        $(this).addClass('on');
          
        //OPEN THE SLIDE
        $(this).next().slideDown('normal');
       } 
        
     });
      
    
    /*** REMOVE IF MOUSEOVER IS NOT REQUIRED ***/
    
    //ADDS THE .OVER CLASS FROM THE STYLESHEET ON MOUSEOVER 
    $('.accordionButton').mouseover(function() {
      $(this).addClass('over');
      
    //ON MOUSEOUT REMOVE THE OVER CLASS
    }).mouseout(function() {
      $(this).removeClass('over');                    
    });
    
    /*** END REMOVE IF MOUSEOVER IS NOT REQUIRED ***/
    
    
    /********************************************************************************************************************
    CLOSES ALL S ON PAGE LOAD
    ********************************************************************************************************************/ 
    $('.accordionContent').hide();

  });

app/views/propuestas/_form.html.haml
= form_for(@propuesta, :validate => true) do |f|

  .clearfix
    = label_tag :descripcion
    .input
      = f.text_field :descripcion
  
  %hr
    .input
      = f.submit :class => 'btn btn-primary'
  

app/views/propuestas/buscar.js.erb
 $("#busqueda_periodos").html("<%= escape_javascript (render :partial => 'busqueda') %>");
<%#= render :partial => 'busqueda'%>

app/views/propuestas/edit.html.haml
.content
  .page-header
    %h1 Editar Propuesta
    = render 'form' 

  = link_to 'Ver',  @propuesta , :class => 'btn'
  = link_to 'Volver', propuestas_path , :class => 'btn'

app/views/propuestas/index.html.haml
.content
  .page-header
    %h1 Propuestas
  .row-fluid
    .span14
      = form_tag buscar_propuestas_path, :remote => true do
        %table
          %tr
            %td Pa&iacute;s
            %td
              = select_tag :pais_id, ("<option>Seleccione</option>"+options_from_collection_for_select(Pais.all,'id','nombre')).html_safe
          %tr.provincia
            %td Provincia
            %td
              = select_tag :provincia_id
          %tr.municipio
            %td Muncipio
            %td
              = select_tag :municipio_id
          %tr.barrio
            %td Barrio
            %td
              = select_tag :barrio_id
              = hidden_field_tag :estre, nil
          %tr
            %td{:colspan=>"2",:style=>"text-align:right;"}
              = image_submit_tag('search_blue.png',:style=>"width:32px;") + 'Buscar'
      #busqueda_periodos        
      

        
            
:javascript
  
  $(document).ready(function(){
    $('#pais_id').change(cambio_pais);
    $("#provincia_id").change(cambio_provincia);
    $("#municipio_id").change(cambio_municipio);

    
  })
  function cambio_pais(){
    jQuery.ajax({
      complete: function(){
                  $('.municipio select').html('<option>Seleccione</option>');
                  $('.barrio select').html('<option>Seleccione</option>');
                },
      type:'get',
      url: "#{busca_provincias_municipios_path}?id="+$('#pais_id').val()
     });
  }

  function cambio_provincia(){
    jQuery.ajax({
       complete:$('.barrio select').html('<option>Seleccione</option>'),
       type:'get',
       url: "#{busca_municipios_barrios_path}?id="+$('#provincia_id').val()
     });
  }

  function cambio_municipio(){
    jQuery.ajax({
       type:'get',
       url: "#{busca_barrios_ciudadanos_path}?id="+$('#municipio_id').val()
     });
  }

app/views/propuestas/new.html.haml
.content
  .page-header
    %h1 Nueva Propuesta
  .row-fluid
    .span14
      = render 'form'
      = link_to 'Volver', propuestas_path, :class => 'btn default'

app/views/propuestas/show.html.haml
.content
  .page-header
    %h1 Propuesta
  .row-fluid
    .span14
    
      %b Descripcion:
      = @propuesta.descripcion 

      %br
    
      %b Propuesta por:
      = link_to "#{@propuesta.user.ciudadano_nombre}" , @propuesta.user.ciudadano if @propuesta.user.ciudadano

      %br
    
      
 
      %hr

 

      = link_to 'Editar', edit_propuesta_path(@propuesta),:class=>'btn btn-info'
      
      = link_to 'Volver', propuestas_path ,:class=>'btn default'