config/routes.rb
Sondeo::Application.routes.draw do
  resources :periodo_electorales do
    member do
      get :show_resultados
      get :show_proyecto
      get :nuevo_anteproyecto
      post :nuevo_proyecto
    end
    collection do
      get :eliminar_proyecto
    end
  end

  resources :periodo_propuestas do
    collection do
      get :nueva_propuesta
      get :propuestas 
    end
  end

  resources :propuestas do 
    collection do
      get :buscar
    end
  end

  resources :municipios do
    collection do
      get "busca_provincias"
    end
  end

  resources :provincias 

  resources :paises 

  get "main/index"

  resources :users do
    collection do
      post 'cambiar_pass'
    end
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'iniciar' => 'sessions#iniciar', :as => :iniciar
  
  match 'mobile' => 'mobile#index', :as => :mobile

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :barrios do
    collection do
      get "busca_municipios"
    end
  end

  resources :ciudadanos do
    member do
      get "anteproyectos"
      post "registrar_voto"
      get 'elecciones_cerradas'
    end

    collection do
      get 'busca_barrios'
      get 'periodos'
    end
  end

  root :to => "main#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/ciudadano.rb
class Ciudadano < ActiveRecord::Base
  belongs_to :barrio
  belongs_to :user	
  has_many :elecciones
  # has_many :anteproyectos,:through => :elecciones

  validates :nombre, :apellido, :email, :dni, :direccion, :telefono, :barrio_id,:user_id, :presence => true
  validates :dni, :telefono, :numericality => true
  validates_uniqueness_of :dni
  
  delegate :nombre, :to => :barrio, :prefix => true

  def municipio_nombre
    barrio.municipio_nombre
  end

  def periodos_abiertos
  	barrio.periodo_propuestas.where("? <= fecha_fin",Date.today)
  end

  def eleccion_abierta
  	barrio.periodo_electorales.where("? <= fecha_fin",Date.today).first
  end

  def elecciones_cerradas
    barrio.periodo_electorales.where("? > fecha_fin",Date.today)
  end

  def alternativas(periodo_electoral)
    Hash[elecciones.includes(:anteproyecto).where('anteproyectos.periodo_electoral_id = ?',periodo_electoral.id).collect{|v| [v.anteproyecto_id,v.etiqueta]}]
  end
  
end

app/controllers/ciudadanos_controller.rb
class CiudadanosController < ApplicationController
  before_filter :login_required, :except=>[:periodos,:registrar_voto]
  skip_before_filter :check_authorization, :only => [:busca_barrios]
  #skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
  # GET /ciudadanos
  # GET /ciudadanos.json
  def index
    @ciudadanos = Ciudadano.paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ciudadanos }
    end
  end

  # GET /ciudadanos/1
  # GET /ciudadanos/1.json
  def show
    @ciudadano = Ciudadano.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @ciudadano }
    end
  end

  # GET /ciudadanos/new
  # GET /ciudadanos/new.json
  def new
    @ciudadano = Ciudadano.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ciudadano }
    end
  end

  # GET /ciudadanos/1/edit
  def edit
    @ciudadano = Ciudadano.find(params[:id])
  end

  # POST /ciudadanos
  # POST /ciudadanos.json
  def create
    password = generar_clave
    params[:ciudadano][:barrio_id] = nil if params[:ciudadano][:barrio_id].to_i == 0 
    @ciudadano = Ciudadano.new(params[:ciudadano])
    @ciudadano.password=password
    @usuario = User.new(
                      :name=>@ciudadano.apellido+" "+@ciudadano.nombre,
                      :login=>@ciudadano.dni,
                      :email=>@ciudadano.email,
                      :password=>password,
                      :password_confirmation=>password
                      )
    @usuario.tipo="ciudadano"
    @usuario.save
    @ciudadano.user_id = @usuario.id
    respond_to do |format|
      if @ciudadano.save 
        format.html { redirect_to @ciudadano, :notice => 'Ciudadano ha sido creado.' }
        format.json { render :json => @ciudadano, :status => :created, :location => @ciudadano }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ciudadano.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ciudadanos/1
  # PUT /ciudadanos/1.json
  def update
    @ciudadano = Ciudadano.find(params[:id])
    params[:ciudadano][:barrio_id] = nil if params[:ciudadano][:barrio_id].to_i == 0 
    respond_to do |format|
      if @ciudadano.update_attributes(params[:ciudadano])
        format.html { redirect_to @ciudadano, :notice => 'Ciudadano ha sido actualizado.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ciudadano.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ciudadanos/1
  # DELETE /ciudadanos/1.json
  def destroy
    @ciudadano = Ciudadano.find(params[:id])
    @ciudadano.destroy

    respond_to do |format|
      format.html { redirect_to ciudadanos_url }
      format.json { head :ok }
    end
  end


  def busca_barrios
    unless params[:id] == 'Seleccione'
      @barrios = Barrio.where("municipio_id = ?", params[:id])
    else
      @barrios = []
    end 
    respond_to do |format|
      format.js
    end
  end


  def periodos
    ciudadano=Ciudadano.find(params[:id])
    respond_to do |format|
      format.json{render :json => ciudadano.periodos_abiertos.to_json }
    end
  end

  def elecciones_cerradas
    ciudadano=Ciudadano.find(params[:id])
    respond_to do |format|
      format.json{render :json => ciudadano.elecciones_cerradas.to_json }
    end
  end

  def anteproyectos
    @ciudadano=Ciudadano.find(params[:id])
    @periodo_electoral=@ciudadano.eleccion_abierta
    @anteproyectos = @periodo_electoral ? @periodo_electoral.anteproyectos_ciudadano(@ciudadano.id) : nil

    respond_to do |format|
      format.html
      format.json{render :json => @anteproyectos.to_json }
    end
  end

  def registrar_voto
    @ciudadano=Ciudadano.find(params[:id])
    @eleccion=Eleccion.where("anteproyecto_id = ? and ciudadano_id = ? ",params[:proyecto_id],@ciudadano.id).first
    @eleccion=Eleccion.new(:anteproyecto_id=>params[:proyecto_id],:ciudadano_id=>@ciudadano.id) if @eleccion.blank?
    unless params[:etiqueta] == "null"
      @eleccion.etiqueta = params[:etiqueta]
      @eleccion.save
    else
      @eleccion.delete
    end
    respond_to do |format|
      format.js
      format.json{render :json=> @eleccion.to_json,:status=>'ok'}
    end
  end
end

app/helpers/ciudadanos_helper.rb
module CiudadanosHelper
end

app/views/ciudadanos/_form.html.haml
= form_for(@ciudadano, :validate => true,:class => 'form-horizontal') do |f| 
     
  .control-group
    = label_tag :dni 
    .controls
      = f.text_field :dni,:class => 'numerico' 
  .clearfix
    = label_tag :nombre 
    .input
      = f.text_field :nombre
  .clearfix
    = label_tag :apellido 
    .input
      = f.text_field :apellido 
  .clearfix
    = label_tag :email
    .input 
      = f.text_field :email 
  .clearfix
    = label_tag :direccion 
    .input
      = f.text_field :direccion 
  .clearfix
    = label_tag :telefono 
    .input
      = f.text_field :telefono,:class => 'numerico'
  .clearfix    
    = label_tag :pais_id 
    .input
      = select_tag :pais_id, ("<option>Seleccione</option>"+options_from_collection_for_select(Pais.all,'id','nombre')).html_safe
  .clearfix.provincia    
    = label_tag :provincia_id 
    .input
      = select_tag :provincia_id,options_from_collection_for_select(Provincia.where("pais_id = ? ", current_user.pais_id ),'id','nombre')
  .clearfix.municipio
    = label_tag :municipio_id 
    .input
      = select_tag :municipio_id,options_from_collection_for_select(Municipio.where("provincia_id = ? ", current_user.provincia_id ),'id','nombre')
  .clearfix.barrio    
    = label_tag :barrio_id 
    .input
      = f.select :barrio_id, Barrio.all.collect{|t| [t.nombre, t.id]}, :include_blank=>"Seleccione"
  
  
  .input

    = f.submit  :class => 'btn btn-primary'
  
:javascript
  $(document).ready(function(){
    //cambio_pais();
    $("#pais_id").change(cambio_pais);
    $("#provincia_id").change(cambio_provincia);
    $("#municipio_id").change(cambio_municipio);

    $(".numerico").keydown(function(event) {
        // Allow: backspace, delete, tab and escape
        if ( event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 27 || 
             // Allow: Ctrl+A
            (event.keyCode == 65 && event.ctrlKey === true) || 
             // Allow: home, end, left, right
            (event.keyCode >= 35 && event.keyCode <= 39)) {
                 // let it happen, don't do anything
                 return;
        }
        else {
            // Ensure that it is a number and stop the keypress
            if ((event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105 )) {
                event.preventDefault(); 
            }   
        }
    });

    
  });

  function cambio_pais(){
    jQuery.ajax({
      complete: function(){
                  $('.municipio select').html('<option>Seleccione</option>');
                  $('.barrio select').html('<option>Seleccione</option>');
                },
      type:'get',
      url: "#{busca_provincias_municipios_path}?id="+$('#pais_id').val()
     });
  }

  function cambio_provincia(){
    jQuery.ajax({
       complete:$('.barrio select').html('<option>Seleccione</option>'),
       type:'get',
       url: "#{busca_municipios_barrios_path}?id="+$('#provincia_id').val()
     });
  }

  function cambio_municipio(){
    jQuery.ajax({
       type:'get',
       url: "#{busca_barrios_ciudadanos_path}?id="+$('#municipio_id').val()
     });
  }

app/views/ciudadanos/anteproyectos.html.erb
<div class="content">
  <div class="page-header">
      <h1>Anteproyectos</h1> 
  </div>

        <%#= link_to image_tag('iconos/folder_add_256.png',:width=>32,:alt=>'')+'Nuevo Anteproyecto', nuevo_anteproyecto_periodo_electoral_path(@periodo_electoral),:class=>'fancybox btn btn-success' %>
        <fieldset>
          <legend>Listado de Anteproyectos</legend>
          <div id="listado_proyectos">
            <table id="tabla_proyectos" class="table table-striped">
              <tr>
                <th>Nombre</th>
                <th>Descripci&oacute;n</th>
                <th></th>
              </tr>
              <% @periodo_electoral.anteproyectos_ciudadano(@ciudadano.id).each do |proyecto| %>
              <tr id="proyecto_<%= "#{proyecto["id"]}" %>">
                <td><%= proyecto["nombre"] %></td>
                <td><%= proyecto["descripcion"][0..40] %></td>
                <td>
                  <%# eleccion = Eleccion.where("anteproyecto_id = ? and ciudadano_id = ? ",proyecto.id,@ciudadano.id).first %>
                  <%= hidden_field_tag "eleccion_#{proyecto["id"]}", proyecto["etiqueta"]  %>
                  <div class="star" id="<%=proyecto["id"]%>"></div>
                  <div class="target" id="target_<%=proyecto["id"]%>" style=" background-color: #F0F0F0; border-radius: 3px; float: left; height: 15px; margin-left: 5px; padding-bottom: 2px; padding-left: 8px; padding-right: 8px; text-align: center; width: 90px; float: left; "></div>
                  <%#= link_to image_tag('iconos/32x32/remove_from_database.png'), eliminar_proyecto_periodo_electorales_path(:id=>proyecto.id), :confirm => '¿Esta seguro?',:title => 'Eliminar', :class => 'qtip',:remote=>true %>
                </td>
              </tr>
              <% end unless @periodo_electoral.blank? %>
            </table>
          </div>
        </fieldset>

</div>  
<script type="text/javascript">
  
  <%= "var hints= ['#{ETIQUETAS[1]["denominacion"].capitalize}','#{ETIQUETAS[2]["denominacion"].capitalize}','#{ETIQUETAS[3]["denominacion"].capitalize}','#{ETIQUETAS[4]["denominacion"].capitalize}','#{ETIQUETAS[5]["denominacion"].capitalize}'];" %>
  $(document).ready(function  () {
    $('.star').each(function  () {
      $(this).raty({  
        cancel     : true,
        cancelHint : 'Ninguno',
        target     : '#target_'+$(this).attr('id'),
        score      : $('#eleccion_' + $(this).attr('id') ).val(),  
        hints : hints,
        click   : function(score, evt) {
              registrar_voto(score, $(this).attr('id'));
            }
      })
      
    })
  })
  function registrar_voto (score,proyecto_id) {
    jQuery.ajax({
       type:'post',
       data: {proyecto_id: proyecto_id, etiqueta: score},
       //url:'<%= registrar_voto_ciudadano_path(current_user.ciudadano) %>'
       url:'<%= registrar_voto_ciudadano_path(@ciudadano.id) %>'
     });
    //alert('score: ' + score + ' proyecto: ' + proyecto_id)
  }
</script>

app/views/ciudadanos/edit.html.haml
.content
  .page-header
    %h1 Editar Ciudadano
    = render 'form' 

  = link_to 'Ver', @ciudadano, :class => 'btn'
  = link_to 'Volver', ciudadanos_path , :class => 'btn'

app/views/ciudadanos/index.html.haml
.content
  .page-header
    %h1 Cuidadanos
  .row-fluid
    .span14
      %table.table.table-striped{:width=>'100%'}
        %tr
          %th Apellido y Nombre
          %th DNI
          %th Email
          %th
          
        - @ciudadanos.each do |ciudadano|
          %tr
            %td
              = link_to "#{ciudadano.apellido}, #{ciudadano.nombre}", ciudadano
              = link_to content_tag(:i, nil, {:class => "icon-pencil", :title => "Editar"}),edit_ciudadano_path(ciudadano)
              = link_to content_tag(:i, nil, {:class => "icon-remove", :title => "Eliminar"}),ciudadano , :confirm => '¿Está Seguro?', :method => :delete
            %td= ciudadano.dni
            %td= ciudadano.email
            %td
             
      %hr
      %center
        = will_paginate @ciudadanos, :renderer => BootstrapPagination::Rails 
      .clearfix
        .input
          = link_to 'Nuevo ciudadano', new_ciudadano_path, :class => 'btn btn-primary'

app/views/ciudadanos/new.html.haml
.content
  .page-header
    %h1 Alta de Nuevo Cuidadano
      
    = render 'form' 

  = link_to 'Volver', ciudadanos_path, :class => 'btn'

app/views/ciudadanos/registrar_voto.js.erb
$('.alert').hide();
<% unless params[:etiqueta] == "null" %>
  $('.alert p').html('Voto cargado');
  $('.alert-success').show();
  setTimeout(function() {$('.alert').hide(500);} , 5000);
<% else %>
  $('.alert p').html('Voto Eliminado');
  $('.alert-error').show();
  setTimeout(function() {$('.alert').hide(500);} , 5000);
<% end %>

app/views/ciudadanos/show.html.haml
.content
  .page-header
    %h1 Cuidadano
  .row-fluid
    .span14

      %b DNI:
      = @ciudadano.dni

      %br

      %b Nombre:
      = @ciudadano.nombre
      
      %br

      %b Apellido:
      = @ciudadano.apellido

      %br

      %b Email:
      = @ciudadano.email

      %br

      %b Direccion:
      = @ciudadano.direccion

      %br

      %b Telefono:
      = @ciudadano.telefono

      %br
      - if current_user.administrador? || current_user.gobierno?
        %b Password:
        = @ciudadano.password
      



      %hr
      = link_to 'Editar',  edit_ciudadano_path(@ciudadano),:class=>'btn btn-info'
      
      = link_to 'Volver',ciudadanos_path  ,:class=>'btn default'