config/routes.rb
Sondeo::Application.routes.draw do
  resources :periodo_electorales do
    member do
      get :show_resultados
      get :show_proyecto
      get :nuevo_anteproyecto
      post :nuevo_proyecto
    end
    collection do
      get :eliminar_proyecto
    end
  end

  resources :periodo_propuestas do
    collection do
      get :nueva_propuesta
      get :propuestas 
    end
  end

  resources :propuestas do 
    collection do
      get :buscar
    end
  end

  resources :municipios do
    collection do
      get "busca_provincias"
    end
  end

  resources :provincias 

  resources :paises 

  get "main/index"

  resources :users do
    collection do
      post 'cambiar_pass'
    end
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'iniciar' => 'sessions#iniciar', :as => :iniciar
  
  match 'mobile' => 'mobile#index', :as => :mobile

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :barrios do
    collection do
      get "busca_municipios"
    end
  end

  resources :ciudadanos do
    member do
      get "anteproyectos"
      post "registrar_voto"
      get 'elecciones_cerradas'
    end

    collection do
      get 'busca_barrios'
      get 'periodos'
    end
  end

  root :to => "main#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/periodo_propuesta.rb
class PeriodoPropuesta < ActiveRecord::Base
  belongs_to :barrio
  belongs_to :municipio

  has_many :propuestas
  
  validates :descripcion, :barrio_id, :municipio_id,:fecha_fin,:fecha_inicio, :presence => true

  delegate :nombre, :to => :municipio, :prefix => 'municipio'
  delegate :pais, :to => :municipio
  delegate :provincia, :to => :municipio 
  delegate :ciudadanos, :to => :barrio , :prefix=>true
  
  def vigente?
    fecha_inicio <= Date.today &&   Date.today <= fecha_fin
  end

  def barrio_nombre
    barrio.nombre unless barrio.blank? 
  end

  def provincia_id
    provincia.id
  end

  def pais_id
    pais.id    
  end

  def pais_nombre
    municipio.pais_nombre
  end

  def provincia_nombre
    municipio.provincia_nombre
  end
end

app/controllers/periodo_propuestas_controller.rb
class PeriodoPropuestasController < ApplicationController
  before_filter :login_required, :except=>[:propuestas]
  # GET /periodo_propuestas
  # GET /periodo_propuestas.json
  def index
    @periodo_propuestas = PeriodoPropuesta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @periodo_propuestas }
    end
  end

  # GET /periodo_propuestas/1
  # GET /periodo_propuestas/1.json
  def show
    @periodo_propuesta = PeriodoPropuesta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @periodo_propuesta }
    end
  end

  # GET /periodo_propuestas/new
  # GET /periodo_propuestas/new.json
  def new
    @periodo_propuesta = PeriodoPropuesta.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @periodo_propuesta }
    end
  end

  # GET /periodo_propuestas/1/edit
  def edit
    @periodo_propuesta = PeriodoPropuesta.find(params[:id])
  end

  # POST /periodo_propuestas
  # POST /periodo_propuestas.json
  def create
    params[:periodo_propuesta][:fecha_fin]=Date.strptime(params[:periodo_propuesta][:fecha_fin],'%d/%m/%Y')
    params[:periodo_propuesta][:fecha_inicio]=Date.strptime(params[:periodo_propuesta][:fecha_inicio],'%d/%m/%Y')
    @periodo_propuesta = PeriodoPropuesta.new(params[:periodo_propuesta])

    respond_to do |format|
      if @periodo_propuesta.save
        format.html { redirect_to @periodo_propuesta, :notice => 'Periodo propuesta fue creado correctamente.' }
        format.json { render :json => @periodo_propuesta, :status => :created, :location => @periodo_propuesta }
      else
        format.html { render :action => "new" }
        format.json { render :json => @periodo_propuesta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /periodo_propuestas/1
  # PUT /periodo_propuestas/1.json
  def update
    @periodo_propuesta = PeriodoPropuesta.find(params[:id])
    params[:periodo_propuesta][:fecha_inicio]=Date.strptime(params[:periodo_propuesta][:fecha_inicio],'%d/%m/%Y') unless params[:periodo_propuesta][:fecha_inicio].blank?
    params[:periodo_propuesta][:fecha_fin]=Date.strptime(params[:periodo_propuesta][:fecha_fin],'%d/%m/%Y') unless params[:periodo_propuesta][:fecha_fin].blank?
    respond_to do |format|
      if @periodo_propuesta.update_attributes(params[:periodo_propuesta])
        format.html { redirect_to @periodo_propuesta, :notice => 'Periodo propuesta fue actualizado correctamente.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @periodo_propuesta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /periodo_propuestas/1
  # DELETE /periodo_propuestas/1.json
  def destroy
    @periodo_propuesta = PeriodoPropuesta.find(params[:id])
    @periodo_propuesta.destroy

    respond_to do |format|
      format.html { redirect_to periodo_propuestas_url }
      format.json { head :ok }
    end
  end

  def propuestas
    @periodo_propuesta = PeriodoPropuesta.find(params[:id])
    @propuestas = @periodo_propuesta.propuestas
    respond_to do |format|
      format.html
      format.json{render :json => @propuestas.to_json}
    end
  end
  def nueva_propuesta
    @propuesta=Propuesta.new
    @periodo_propuesta = PeriodoPropuesta.find(params[:id])
    #@propuestas = @periodo_propuesta.propuestas
    respond_to do |format|
      format.html
      #format.json{render :json => @propuestas.to_json}
    end
  end

end

app/helpers/periodo_propuestas_helper.rb
module PeriodoPropuestasHelper
end

app/views/periodo_propuestas/_form.html.haml
= form_for(@periodo_propuesta, :validate => true) do |f|

  #alert.alert.alert-error{:style=>'display:none;'}
    %strong
  .clearfix
    = label_tag :descripcion
    .input
      = f.text_field :descripcion
  .clearfix
    = label_tag :fecha_inicio, 'Fecha de Inicio'
    .input-append.date
      = f.text_field :fecha_inicio, :readonly => "readonly"
      %span#fecha_ini.add-on
        %i.icon-calendar
  .clearfix
    = label_tag :fecha_fin, 'Fecha de Fin'
    .input-append.date
      = f.text_field :fecha_fin, :readonly => "readonly",:class=>'small'
      %span#fecha_fin.add-on
        %i.icon-calendar
  .clearfix
    = label_tag :pais_id
    .input
      = select_tag :pais_id, ("<option value=\"\">Seleccione</option>" + options_from_collection_for_select(Pais.all,'id','nombre',@periodo_propuesta.barrio ? @periodo_propuesta.pais_id : 0)).html_safe
  .clearfix.provincia
    = label_tag :provincia_id
    .input
      = select_tag :provincia_id, ("<option value=\"\">Seleccione</option>" + options_from_collection_for_select(Provincia.where('pais_id = ?',@periodo_propuesta.barrio ? @periodo_propuesta.pais_id : 0),'id','nombre',@periodo_propuesta.barrio ? @periodo_propuesta.provincia_id : 0)).html_safe
  .clearfix.municipio
    = label_tag :municipio_id
    .input
      = f.select :municipio_id, ("<option value=\"\">Seleccione</option>" + options_from_collection_for_select(Municipio.where('provincia_id = ?',@periodo_propuesta.barrio ? @periodo_propuesta.provincia_id : 0),'id','nombre',@periodo_propuesta.barrio_id ? @periodo_propuesta.municipio_id : 0)).html_safe
  .clearfix.barrio
    = label_tag :barrio_id
    .input
      = f.select :barrio_id, ("<option value=\"\">Seleccione</option>" + options_from_collection_for_select(Barrio.where('municipio_id = ?',@periodo_propuesta.municipio_id),'id','nombre',@periodo_propuesta.barrio ? @periodo_propuesta.barrio_id : 0)).html_safe
  
  %hr
    .input
      = f.submit :class => 'btn btn-primary'

:javascript
  $(document).ready(function(){

    $('#pais_id').change(cambio_pais);
    $('#provincia_id').change(cambio_provincia);
    $('#periodo_propuesta_municipio_id').change(cambio_municipio);

    var fecha_ini = '#{@periodo_propuesta.fecha_inicio.blank? ? format_fecha(Date.today) : format_fecha(@periodo_propuesta.fecha_inicio)}'
    var fecha_fin = '#{@periodo_propuesta.fecha_fin.blank? ? format_fecha(Date.today) : format_fecha(@periodo_propuesta.fecha_fin)}'
    $('#periodo_propuesta_fecha_inicio').val(fecha_ini);
    $('#periodo_propuesta_fecha_fin').val(fecha_fin);
    $('#periodo_propuesta_fecha_inicio').datepicker({format: 'dd/mm/yyyy'})
        .on('changeDate', function(ev){
          fin = $('#periodo_propuesta_fecha_fin').val();
          var endDate = new Date(fin.split('/')[2],fin.split('/')[1] - 1,fin.split('/')[0]);
          if (ev.date.valueOf() > endDate.valueOf()){
            $('#alert').show().find('strong').text('Fecha de Inicio no puede ser mayor a la Fecha de Fin');
          } else {
            $('#alert').hide();
            
          }
          $('#periodo_propuesta_fecha_inicio').datepicker('hide');
        
        });
    $('#periodo_propuesta_fecha_fin').datepicker({format: 'dd/mm/yyyy'})
        .on('changeDate', function(ev){
          incio = $('#periodo_propuesta_fecha_inicio').val();
          var startDate = new Date(incio.split('/')[2],incio.split('/')[1] - 1,incio.split('/')[0]);
          if (startDate.valueOf() > ev.date.valueOf()){
            $('#alert').show().find('strong').text('Fecha de Inicio no puede ser mayor a la Fecha de Fin');
          } else {
            $('#alert').hide();
            
          }
          $('#periodo_propuesta_fecha_fin').datepicker('hide');
        
        });
    $('#fecha_fin').click(function(){
      $('#periodo_propuesta_fecha_fin').datepicker('show');
    })
    $('#fecha_ini').click(function(){
      $('#periodo_propuesta_fecha_inicio').datepicker('show');
    })
    $('form').submit(function(){
      return form_valid();
    })
  });
  function form_valid(){
    incio = $('#periodo_propuesta_fecha_inicio').val();
    var startDate = new Date(incio.split('/')[2],incio.split('/')[1] - 1,incio.split('/')[0]);
    fin = $('#periodo_propuesta_fecha_fin').val();
    var endDate = new Date(fin.split('/')[2],fin.split('/')[1] - 1,fin.split('/')[0]);
    if (startDate.valueOf() > endDate.valueOf()){
      $('#alert').show().find('strong').text('Fecha de Inicio no puede ser mayor a la Fecha de Fin');
      return false;
    } else {
      $('#alert').hide();
      return true;
    }
  }

  function cambio_pais(){
    jQuery.ajax({
      complete: function(){
                  $('.municipio select').html('<option>Seleccione</option>');
                  $('.barrio select').html('<option>Seleccione</option>');
                },
      type:'get',
      url: "#{busca_provincias_municipios_path}?id="+$('#pais_id').val()
     });
  }

  function cambio_provincia(){
    jQuery.ajax({
       complete:$('.barrio select').html('<option>Seleccione</option>'),
       type:'get',
       url: "#{busca_municipios_barrios_path}?id="+$('#provincia_id').val()
     });
  }

  function cambio_municipio(){
    jQuery.ajax({
       type:'get',
       url: "#{busca_barrios_ciudadanos_path}?id="+$('#periodo_propuesta_municipio_id').val()
     });
  }
  

app/views/periodo_propuestas/edit.html.haml
.content
  .page-header
    %h1 Editar Per&iacute;odo de Propuesta
    = render 'form' 

  = link_to 'Ver',  @periodo_propuesta , :class => 'btn btn-info'
  = link_to 'Volver', periodo_propuestas_path , :class => 'btn'

app/views/periodo_propuestas/index.html.haml
.content
  .page-header
    %h1 Per&iacute;odos de Propuestas
  .row-fluid
    .span14
      %table.table.table-striped{:width=>'100%'}
        %tr
          %th Descripcion
          %th Fecha inicio
          %th Fecha fin
          %th Pais
          %th Provincia
          %th Municipio
          %th Barrio

          
        - @periodo_propuestas.each do |periodo_propuesta|
          %tr
            %td
              =link_to periodo_propuesta.descripcion, periodo_propuesta
            
              = link_to content_tag(:i, nil, {:class => "icon-pencil", :title => "Editar"}),edit_periodo_propuesta_path(periodo_propuesta) if current_user.administrador? 
              = link_to content_tag(:i, nil, {:class => "icon-plus", :title => "Propuestas"}),propuestas_periodo_propuestas_path(:id=>periodo_propuesta.id) if periodo_propuesta.vigente? 
              = link_to content_tag(:i, nil, {:class => "icon-remove", :title => "Eliminar"}),periodo_propuesta , :confirm => '¿Está Seguro?', :method => :delete if current_user.administrador?
            %td= format_fecha periodo_propuesta.fecha_inicio 
            %td= format_fecha periodo_propuesta.fecha_fin 
            %td= periodo_propuesta.pais_nombre 
            %td= periodo_propuesta.provincia_nombre
            %td= periodo_propuesta.municipio_nombre
            %td= periodo_propuesta.barrio_nombre 
      
      -if current_user.administrador? || current_user.gobierno?      
        %hr
        .clearfix
          .input
            = link_to 'Nuevo Periodo propuesta', new_periodo_propuesta_path, :class => 'btn btn-primary'

app/views/periodo_propuestas/new.html.haml
.content
  .page-header
    %h1 Nuevo Per&iacute;odo de Propuesta
  .row-fluid
    .span14
      = render 'form'
      = link_to 'Volver', periodo_propuestas_path, :class => 'btn default'

app/views/periodo_propuestas/nueva_propuesta.html.haml
.content
  .page-header
    %h1 Nueva Propuesta
  .row-fluid
    .span14

      = form_for(@propuesta, :validate => true) do |f|
        
        .clearfix
          = label_tag :descripcion,"Descripción"
          .input
            = f.text_field :descripcion
            = f.hidden_field :user_id, :value => current_user.id
            = f.hidden_field :periodo_propuesta_id, :value => @periodo_propuesta.id
        
        %hr
          .input
            = f.submit :class => 'btn btn-primary'
  
      = link_to 'Volver', propuestas_path, :class => 'btn default'

app/views/periodo_propuestas/propuestas.html.haml
.content
  .page-header
    %h1 Propuestas del Per&iacute;odo "#{@periodo_propuesta.descripcion}"
  .row-fluid
    .span14
      %table.table.table-striped{:width=>'100%'}
        %tr
          %th Descripci&oacute;n
          %th Usuario
         
          %th
          
        - @propuestas.each do |propuesta|
          %tr
            %td
              
              =link_to propuesta.descripcion, propuesta
            
              = link_to content_tag(:i, nil, {:class => "icon-pencil", :title => "Editar"}),edit_propuesta_path(propuesta) if current_user.administrador? || current_user.id == propuesta.user_id
             
              = link_to content_tag(:i, nil, {:class => "icon-remove", :title => "Eliminar"}),propuesta , :confirm => '¿Está Seguro?', :method => :delete if current_user.administrador? || current_user.id == propuesta.user_id
            %td= propuesta.user.ciudadano_nombre 
            %td
              = link_to image_tag('iconos/32x32/zoom_in.png'), propuesta, :title => 'Ver', :class => 'qtip'
              = link_to image_tag('iconos/32x32/edit_page.png'), edit_propuesta_path(propuesta), :title => 'Editar', :class => 'qtip'
              = link_to image_tag('iconos/32x32/remove_from_database.png'),propuesta , :confirm => 'Are you sure?', :method => :delete, :title => 'Eliminar', :class => 'qtip'
      %hr
      .clearfix
        .input
          = link_to 'Nueva propuesta', nueva_propuesta_periodo_propuestas_path(:id=>@periodo_propuesta.id), :class => 'btn btn-primary'

app/views/periodo_propuestas/show.html.haml
.content
  .page-header
    %h1 Per&iacute;odo de Propuesta
  .row-fluid
    .span14
    
      %b Descripci&oacute;n:
      = @periodo_propuesta.descripcion 

      %br
    
      %b Fecha inicio:
      = format_fecha @periodo_propuesta.fecha_inicio 

      %br
    
      %b Fecha fin:
      = format_fecha @periodo_propuesta.fecha_fin 

      %br

      %b Pa&iacute;s:
      = @periodo_propuesta.pais_nombre

      %br

      %b Provincia:
      = @periodo_propuesta.provincia_nombre      

      %br

      %b Municipio:
      = @periodo_propuesta.municipio_nombre
    
      %br
    
      %b Barrio:
      = @periodo_propuesta.barrio_nombre 

      %br
      
 
      %hr

 

      = link_to 'Editar', edit_periodo_propuesta_path(@periodo_propuesta),:class=>'btn btn-info' if current_user.administrador?
      
      = link_to 'Volver', periodo_propuestas_path ,:class=>'btn default'