config/routes.rb
Sondeo::Application.routes.draw do
  resources :periodo_electorales do
    member do
      get :show_resultados
      get :show_proyecto
      get :nuevo_anteproyecto
      post :nuevo_proyecto
    end
    collection do
      get :eliminar_proyecto
    end
  end

  resources :periodo_propuestas do
    collection do
      get :nueva_propuesta
      get :propuestas 
    end
  end

  resources :propuestas do 
    collection do
      get :buscar
    end
  end

  resources :municipios do
    collection do
      get "busca_provincias"
    end
  end

  resources :provincias 

  resources :paises 

  get "main/index"

  resources :users do
    collection do
      post 'cambiar_pass'
    end
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'iniciar' => 'sessions#iniciar', :as => :iniciar
  
  match 'mobile' => 'mobile#index', :as => :mobile

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :barrios do
    collection do
      get "busca_municipios"
    end
  end

  resources :ciudadanos do
    member do
      get "anteproyectos"
      post "registrar_voto"
      get 'elecciones_cerradas'
    end

    collection do
      get 'busca_barrios'
      get 'periodos'
    end
  end

  root :to => "main#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_menu_admin.html.haml
.container
  %a.brand{:href=>'/main'} S. E. C.

  %ul.nav
    -if current_user.administrador?
      %li.dropdown
        %a.dropdown-toggle{:href=> "#",:data=>{:toggle => 'dropdown'} } Usuarios
        %ul.dropdown-menu
          %li 
            = link_to 'Nuevo Usuario', new_user_path
          %li 
            = link_to 'Listado de Usuarios', users_path
            
    %li.dropdown
      %a.dropdown-toggle{:href=> "#","data-toggle".to_sym => 'dropdown' } Ciudadanos
      %ul.dropdown-menu
        %li 
          = link_to 'Nuevo Ciudadano', new_ciudadano_path            
        %li 
          = link_to 'Listado de Ciudadanos', ciudadanos_path            
           
  .pull-right
    .cerrar-session
      .btn-group.pull-right
        %a.btn.dropdown-toggle{:href=>'#', "data-toggle".to_sym=>"dropdown"}
          %i.icon-user
          = current_user.name
        %ul.dropdown-menu
          %li
            %a{:href => '/logout'} Cerrar Sesion

app/views/layouts/_menu_administrador.html.haml
.well.sidebar-nav
  %ul.nav.nav-list
    -if current_user.administrador?
      %li.nav-header Administrador
      %li= link_to 'Paises', paises_path
      %li= link_to 'Provincias', provincias_path
      %li= link_to 'Municipios', municipios_path
      %li= link_to 'Barrios', barrios_path
      %li.divider
    
    -if current_user.administrador? || current_user.gobierno?
      %li.nav-header Propuesta
      %li= link_to 'Periodos de Propuestas', periodo_propuestas_path
      %li= link_to 'Periodos Electorales', periodo_electorales_path

app/views/layouts/_menu_cuidadanos.html.haml
.container
  %a.brand{:href=>'/main'} S. E. C.
  %ul.nav
    %li.dropdown
      %a.dropdown-toggle{:href=> "#","data-toggle".to_sym => 'dropdown' } Propuestas
      %ul.dropdown-menu
        %li 
          = link_to 'Propuestas', propuestas_path
        %li 
          = link_to 'Periodos de Propuestas', periodo_propuestas_path 
    %li.dropdown
      %a.dropdown-toggle{:href=> "#","data-toggle".to_sym => 'dropdown' } Elecciones
      %ul.dropdown-menu
        %li 
          = link_to 'Anteproyectos', anteproyectos_ciudadano_path(current_user.ciudadano)
        %li 
          = link_to 'Periodos de Elecciones', periodo_electorales_path
    
  .pull-right
    .cerrar-session
      .btn-group.pull-right
        %a.btn.dropdown-toggle{:href=>'#', "data-toggle".to_sym=>"dropdown"}
          %i.icon-user
          = current_user.name
        %ul.dropdown-menu
          %li
            %a{:href => '/logout'} Cerrar Sesion

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sondeo
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:name=>"viewport", :content=>"width=device-width, initial-scale=1.0"}
    %meta{:name=>"description", :content=>""}
    %meta{:name=>"author", :content=>""}
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container-fluid
          - if current_user
            - if current_user.ciudadano?
              = render :partial => 'layouts/menu_cuidadanos'
            - if current_user.administrador? ||  current_user.gobierno?
              = render :partial => 'layouts/menu_admin'
    

    .container-fluid
      .row-fluid
        .span3
          
            
          -if current_user.administrador? ||  current_user.gobierno?
            = render :partial => 'layouts/menu_administrador'
          .alert.alert-error{:style=>"#{ 'display:none' if flash[:error].blank?}"}
            %a.close{:href=>"javascript:cierra_mensaje();"} ×
            %p
              = flash[:error] unless flash[:error].blank?

          .alert.alert-success{:style=>"#{ 'display:none' if flash[:notice].blank?}"}
            %a.close{:href=>"javascript:cierra_mensaje();"} ×
            %p
              = flash[:notice] unless flash[:notice].blank?

        .span9
          .row-fluid
            .span9
              .container
              
                = yield

      %footer

:javascript
  $(document).ready(function(){
    $('.qtip').tipTip();
    $('.fancybox').fancybox();
    setTimeout(function() {$('.alert').hide(500);} , 5000);
  });

   jQuery('.submenu').hover(function () {
        jQuery(this).children('ul').removeClass('submenu-hide').addClass('submenu-show');
    }, function () {
        jQuery(this).children('ul').removeClass('.submenu-show').addClass('submenu-hide');
    }).find("a:first").append(" &raquo; ");

  function cierra_mensaje(){
    $('.alert').hide();
  }

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1" />
        <title>
        </title>
        
        <style>
            /* App custom styles */
            div.graph
        {
            width: 230px;
            height: 230px;
            float: left;
            border: 1px dashed gainsboro;
        }
        </style>

        <%= stylesheet_link_tag    "mobile" %> 
        <%= javascript_include_tag "mobile" %>

       

    <body>
        <%= yield %> 
    </body>
</html>

app/views/layouts/sinsession.html.haml
!!!
%html
  %head
    %title Sondeo
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application_falso"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand Bienvenido
                   
          .pull-right
            = form_tag session_path, :class=>'form-horizontal' do 
              
                 
              = text_field_tag 'login', @login, :placeholder => "usuario", :class=>"input-small" 
  
              = password_field_tag 'password', nil , :placeholder => "password", :class=>"input-small" 

              =# label_tag 'remember_me', 'Remember me' 
              =# check_box_tag 'remember_me', '1', @remember_me 

              = submit_tag 'Iniciar', :class => "btn"
    .container
      - unless flash[:error].blank?
        %br
        .alert.alert-error
          %a.close{:href=>"javascript:cerrar_alert()"} ×
          
          = flash[:error]

      - unless flash[:notice].blank?
        %br
        .alert.alert-success
          %a.close{:href=>"javascript:cerrar_alert()"} ×
          
          = flash[:error]
              
      = yield

:javascript
  $(document).ready(function(){
    $('.alert-message').delay(2000).fadeOut(400);
  });
  function cerrar_alert(){
    $('.alert').hide();
  }